config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: {omniauth_callbacks: "users/omniauth_callbacks", registrations: "registrations"}
  root to: 'items#index'
  resources :items, only: [:index, :new, :create, :show, :edit, :destroy, :update] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get "buy"
      get 'done'
      post "pay"
    end
  end
  resources :users, only: [:index,:new, :edit, :show] do
    collection do
      get "logout"
      get "check"
    end 
  end
  resources :signup, only: [:create] do
    collection do
      get "detail"
      get "phone_number"
      get "address"
      get "fin"
    end 
  end
  resources :cards, only: [:create, :new] 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook google_oauth2]
  has_many :cards
  has_one :address
  accepts_nested_attributes_for :address
  has_many :items

  #omniauth_callbacks_controllerで呼び出すメソッド
  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    user = User.where(uid: uid, provider: provider).first #firstをつけないとデータが配列で返されて使いたいメソッドが使えなくて困る
   #sns_credentialsが登録されている
   if user.present?
       return user
    else
      #  userが登録されていない
      new_user  = User.new(
         nickname: auth.info.name,
         email: auth.info.email,
         uid: auth.uid,
         provider: auth.provider,
         )
        return new_user
    end
  end
  
  validates :nickname, presence: true, length: {maximum: 20}
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: {minimum: 7, maximum: 128}
  validates :birthday, presence: true
  validates :last_name_kana, :first_name_kana, presence: true, format: { with: /\A[ア-ン゛゜ァ-ォャ-ョー「」、]+\z/}
  validates :last_name, :first_name, presence: true, format: { with: /\A[ぁ-んァ-ヶー一-龠]+\z/}
  # phone_number入力項目
  validates :phone_number, presence: true,uniqueness: true,numericality: {only_integer: true}
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end

  def show
    self.resource = resource_class.confirm_by_token(params[:confirmation_token])
    yield resource if block_given?

    if resource.errors.empty?
      set_flash_message(:notice, :confirmed) if is_flashing_format?

      sign_in(resource) #<== この一行を加えるのみ

      respond_with_navigational(resource){ redirect_to after_confirmation_path_for(resource_name, resource) }
    else
      respond_with_navigational(resource.errors, :status => :unprocessable_entity){ render :new }
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_for :facebook
  end

  def google_oauth2
    callback_for :google
  end

  # common callback method
  def callback_for(provider)
    provider = provider.to_s
    @user = User.find_oauth(request.env["omniauth.auth"])
    # persisted?はデータがDBに保存されているかを確認する/配列に対しては使えないから@userを定義するときは気をつける
    if @user.persisted?
      #保存されていればログインしてroot_pathにリダイレクトされる
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      # 登録するアクションに取得した値を渡すために。sessionを利用してuserインスタンスを作成する
      session[:nickname] = @user.nickname
      session[:email] = @user.email
      session[:password] = @user.password
      session[:provider] = @user.provider
      session[:uid] = @user.uid
      #snsでのユーザ登録ではパスワードを入力させないので準備する。パスワードを作成するDeviseメソッドもある。
      #今回のバリデーションは英数字のみなのでこっちを採用
      session[:password_confirmation] = SecureRandom.alphanumeric(30)

      #登録フォームのviewにリダイレクトさせる
      redirect_to detail_signup_index_path
    end
  end

  def failure
    redirect_to root_path
  end

 end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController


#   def create
#     @user = User.new(
#       provider: session[:provider], 
#       uid: session[:uid],
#     )
#     if @user.save
#       # ログインするための情報を保管
#       session[:id] = @user.id
#       redirect_to done_signup_index_path
#     else
#       render '/signup/registration'
#     end
#   def done
#     sign_in User.find(session[:id]) unless user_signed_in?
#   end
# end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def callback
    auth = request.env['omniauth.auth']

    user = User.find_by(provider: auth['provider'], uid: auth['uid']) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end
  
  def new
    @user=User.new
  end

  def show
    
  end

  def edit
  end

  def check
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_new-header.html.haml
.header
  = link_to root_path do
    = image_tag 'fmarket_logo_red.png', class: 'header__logo'

app/views/users/check.html.haml
//ユーザー本人確認ページ
=render "items/header"
.mypage-header
  .mypage-header__list
    =render 'shared/breadcrumbs'

//右側ユーザー名
.mypage-main
  .cotent-u
    .content-user
      .user-info
        %h2.user-info__header
          本人情報の登録

        .user-info__main
          %p.user-info__main__text
            お客さまの本人情報をご登録ください。
            %br
            登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
            = link_to '#', class: 'info-link' do
              本人確認書類のアップロードについて
              = fa_icon 'chevron-right'

          %h4.form-title
            お名前
          %p.user-info-p
            = current_user.first_name
            = current_user.last_name

          %h4.form-title
            お名前カナ
          %p.user-info-p
            = current_user.first_name_kana
            = current_user.last_name_kana

          %h4.form-title
            生年月日
          %p.user-info-p
            = current_user.birthday

          %h4.form-title
            郵便番号
            %span.form-arbitrary
              任意
          %input{placeholder: "例）1234567", class: 'form-size form-style'}

          %h4.form-title
            都道府県
            %span.form-arbitrary
              任意
          %select{class: 'form-select form-style'}
            %option --

          %h4.form-title
            市区町村
            %span.form-arbitrary
              任意
          %input{placeholder: "例)横浜市緑区", class: 'form-size form-style'}

          %h4.form-title
            番地
            %span.form-arbitrary
              任意
          %input{placeholder: "例)青山1-1-1", class: 'form-size form-style'}

          %h4.form-title
            建物名
            %span.form-arbitrary
              任意
          %input{placeholder: "例)柳ビル103", class: 'form-size form-style'}

          %button.red-btn
            登録する

          = link_to '#', class: 'user-info__main__link info-link' do
            本人情報の登録について
            = fa_icon 'chevron-right'

  //左側のリスト
  .mypage-main__left
    %nav.mypage-main__left__nav
      %ul.mypage-main__left__nav__list
        = link_to user_path(current_user) do
          %li.mypage-main__left__nav__list__item
            マイページ
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            お知らせ
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            やることリスト
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            いいね！一覧
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            出品する
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            出品した商品-出品中
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            出品した商品-取引中
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            出品した商品-売却済み
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            購入した商品-取引中
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            購入した商品-過去の取引
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            ニュース一覧
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            評価一覧
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            ガイド
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            お問い合わせ
            .mypage-main__left__nav__list__item__icon
      .mypage-main__left__nav__head
        メルペイ
      %ul.mypage-main__left__nav__list
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            残高・振込申請
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            ポイント
            .mypage-main__left__nav__list__item__icon
      .mypage-main__left__nav__head
        設定
      %ul.mypage-main__left__nav__list
        = link_to edit_user_path(current_user) do
          %li.mypage-main__left__nav__list__item
            プロフィール
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            発送元・お届け先住所変更
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            支払い変更
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            メール/パスワード
            .mypage-main__left__nav__list__item__icon
        = link_to check_users_path(current_user) do
          %li.mypage-main__left__nav__list__item
            本人情報
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            電話番号の確認
            .mypage-main__left__nav__list__item__icon
        = link_to logout_users_path(current_user) do
          %li.mypage-main__left__nav__list__item
            ログアウト
            .mypage-main__left__nav__list__item__icon
=render "items/footer"

app/views/users/edit.html.haml
//プロフィール編集 view
//上部
= render 'items/header'
.mypage-header
  .mypage-header__list
    =render 'shared/breadcrumbs'

//右側ユーザー名
.mypage-main
  .mypage-main__profile
    .mypage-main__profile__head
      プロフィール
    .mypage-main__profile__name
      .mypage-main__profile__name__icon
        = image_tag "iconmonstr-user-5-240.png",class:"mypage-main__right__user__main__icon__image"
      %textarea{class:"mypage-main__profile__name__nickname",placeholder:"例)AYA☆セール中"}
    .mypage-main__profile__input
      %textarea{class:"mypage-main__profile__input__text",placeholder:"例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪"}
      = link_to "#" do
        %button.mypage-main__profile__input__btn
          変更する

  //左側のリスト
  .mypage-main__left
    %nav.mypage-main__left__nav
      %ul.mypage-main__left__nav__list
        = link_to user_path(current_user) do
          %li.mypage-main__left__nav__list__item
            マイページ
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            お知らせ
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            やることリスト
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            いいね！一覧
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            出品する
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            出品した商品-出品中
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            出品した商品-取引中
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            出品した商品-売却済み
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            購入した商品-取引中
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            購入した商品-過去の取引
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            ニュース一覧
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            評価一覧
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            ガイド
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            お問い合わせ
            .mypage-main__left__nav__list__item__icon
      .mypage-main__left__nav__head
        メルペイ
      %ul.mypage-main__left__nav__list
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            残高・振込申請
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            ポイント
            .mypage-main__left__nav__list__item__icon
      .mypage-main__left__nav__head
        設定
      %ul.mypage-main__left__nav__list
        = link_to edit_user_path(current_user) do
          %li.mypage-main__left__nav__list__item
            プロフィール
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            発送元・お届け先住所変更
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            支払い変更
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            メール/パスワード
            .mypage-main__left__nav__list__item__icon
        = link_to check_users_path(current_user) do
          %li.mypage-main__left__nav__list__item
            本人情報
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            電話番号の確認
            .mypage-main__left__nav__list__item__icon
        = link_to logout_users_path(current_user) do
          %li.mypage-main__left__nav__list__item
            ログアウト
            .mypage-main__left__nav__list__item__icon
= render 'items/footer'

app/views/users/logout.html.haml
//ログアウト view
=render "items/header"
//上部
.mypage-header
  .mypage-header__list
    =render 'shared/breadcrumbs'

//右側ユーザー名
.mypage-logout
  .mypage-logout__right
    .mypage-logout__right__btn
      = link_to destroy_user_session_path, method: :delete do
        .mypage-logout__right__btn__out
          ログアウト

  //左側のリスト
  .mypage-main__left
    %nav.mypage-main__left__nav
      %ul.mypage-main__left__nav__list
        = link_to user_path(current_user) do
          %li.mypage-main__left__nav__list__item
            マイページ
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            お知らせ
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            やることリスト
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            いいね！一覧
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            出品する
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            出品した商品-出品中
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            出品した商品-取引中
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            出品した商品-売却済み
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            購入した商品-取引中
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            購入した商品-過去の取引
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            ニュース一覧
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            評価一覧
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            ガイド
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            お問い合わせ
            .mypage-main__left__nav__list__item__icon
      .mypage-main__left__nav__head
        メルペイ
      %ul.mypage-main__left__nav__list
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            残高・振込申請
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            ポイント
            .mypage-main__left__nav__list__item__icon
      .mypage-main__left__nav__head
        設定
      %ul.mypage-main__left__nav__list
        = link_to edit_user_path(current_user) do
          %li.mypage-main__left__nav__list__item
            プロフィール
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            発送元・お届け先住所変更
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            支払い変更
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            メール/パスワード
            .mypage-main__left__nav__list__item__icon
        = link_to check_users_path(current_user) do
          %li.mypage-main__left__nav__list__item
            本人情報
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            電話番号の確認
            .mypage-main__left__nav__list__item__icon
        = link_to logout_users_path(current_user) do
          %li.mypage-main__left__nav__list__item
            ログアウト
            .mypage-main__left__nav__list__item__icon
=render "items/footer"

app/views/users/show.html.haml
//上部
=render "items/header"
.mypage-header
  .mypage-header__list
    =render 'shared/breadcrumbs'

//右側ユーザー名
.mypage-main
  .mypage-main__right
    .mypage-main__right__user
      = link_to "#" do 
        = image_tag "mypage.jpg"
        .mypage-main__right__user__main
          .mypage-main__right__user__main__icon
            = image_tag "iconmonstr-user-5-240.png",class:"mypage-main__right__user__main__icon__image"
          .mypage-main__right__user__main__name
            = current_user.nickname
          .mypage-main__right__user__main__count
            評価 0   出品数 0
            .mypage-main__right__user__main__count__action
              
            .mypage-main__right__user__main__count__item

    //お知らせ、やることリスト
    .mypage-main__right__todo
      .mypage-main__right__todo__tab
        = link_to "#" do
          .mypage-main__right__todo__tab__news1
            お知らせ
        = link_to "#" do
          .mypage-main__right__todo__tab__news2
            やることリスト
      .mypage-main__right__todo__content
        = image_tag "mypage1.svg", class:"mypage-main__right__todo__active"
        .mypage-main__right__todo__found

    //購入した商品
    .mypage-main__right__buy
      .mypage-main__right__buy__head
        購入した商品
      .mypage-main__right__todo__tab
        = link_to "#" do
          .mypage-main__right__todo__tab__news1
            取引中
        = link_to "#" do
          .mypage-main__right__todo__tab__news2
            過去の取引
      .mypage-main__right__todo__content
        = image_tag "mypage2.svg", class:"mypage-main__right__todo__active"
        .mypage-main__right__todo__found
        
  //左側のリスト
  .mypage-main__left
    %nav.mypage-main__left__nav
      %ul.mypage-main__left__nav__list
        = link_to user_path(current_user) do
          %li.mypage-main__left__nav__list__item
            マイページ
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            お知らせ
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            やることリスト
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            いいね！一覧
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            出品する
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            出品した商品-出品中
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            出品した商品-取引中
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            出品した商品-売却済み
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            購入した商品-取引中
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            購入した商品-過去の取引
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            ニュース一覧
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            評価一覧
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            ガイド
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            お問い合わせ
            .mypage-main__left__nav__list__item__icon
      .mypage-main__left__nav__head
        メルペイ
      %ul.mypage-main__left__nav__list
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            残高・振込申請
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            ポイント
            .mypage-main__left__nav__list__item__icon
      .mypage-main__left__nav__head
        設定
      %ul.mypage-main__left__nav__list
        = link_to edit_user_path(current_user) do
          %li.mypage-main__left__nav__list__item
            プロフィール
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            発送元・お届け先住所変更
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            支払い変更
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            メール/パスワード
            .mypage-main__left__nav__list__item__icon
        = link_to check_users_path(current_user) do
          %li.mypage-main__left__nav__list__item
            本人情報
            .mypage-main__left__nav__list__item__icon
        = link_to "#" do
          %li.mypage-main__left__nav__list__item
            電話番号の確認
            .mypage-main__left__nav__list__item__icon
        = link_to logout_users_path(current_user) do
          %li.mypage-main__left__nav__list__item
            ログアウト
            .mypage-main__left__nav__list__item__icon
=render "items/footer"