config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: {omniauth_callbacks: "users/omniauth_callbacks", registrations: "registrations"}
  root to: 'items#index'
  resources :items, only: [:index, :new, :create, :show, :edit, :destroy, :update] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get "buy"
      get 'done'
      post "pay"
    end
  end
  resources :users, only: [:index,:new, :edit, :show] do
    collection do
      get "logout"
      get "check"
    end 
  end
  resources :signup, only: [:create] do
    collection do
      get "detail"
      get "phone_number"
      get "address"
      get "fin"
    end 
  end
  resources :cards, only: [:create, :new] 
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images, allow_destroy: true

  belongs_to :category

  has_one :brand, dependent: :destroy
  accepts_nested_attributes_for :brand, allow_destroy: true
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :size
  belongs_to_active_hash :state
  belongs_to_active_hash :postage_side
  belongs_to_active_hash :send_method
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :send_date
  belongs_to :user
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_all, only: [:index, :new, :create, :show, :edit, :update]
  before_action :set_item, only: [:show, :edit, :destroy, :update,:buy,:pay]
  before_action :set_item_image, only: [:index, :show]
  before_action :set_card, only: [:buy, :pay]
  before_action :set_item_category, only: [:new,:create,:edit,:update]
  require 'payjp'


  def index
    @items = Item.includes(:user).order("created_at DESC")
  end

  def new
    @item = Item.new
    @item.item_images.build
    @item.build_brand
  end

  def get_category_children
    @children = Category.find_by(name: params[:parent_name], ancestry: nil).children
  end

  def get_category_grandchildren
    @grandchildren = Category.find(params[:child_id]).children
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      params[:item_images]['image'].each do |a|
        @item.item_images.create!(image: a)
      end
      redirect_to root_path
    else
      @item.item_images.build
      @item.build_brand
      render :new
    end
  end

  def show
    @images = @item.item_images
    @items = Item.includes(:user)
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render_to_string new_item_path
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      render :show
    end
  end


  def category
    respond_to do |format|
      format.html
      format.json do
       @children = Category.find(params[:parent_id]).children
       #親ボックスのidから子ボックスのidの配列を作成してインスタンス変数で定義
      end
    end
  end
  
  def buy
    @address_info = current_user.address.prefecture.name + current_user.address.city + current_user.address.house_number + current_user.address.build_number
    @full_name = current_user.last_name + current_user.first_name
    if  @card.blank?
      redirect_to new_card_path
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def pay
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    Payjp::Charge.create(
    amount: @item.price, #支払金額を入力（itemテーブル等に紐づけても良い）
    customer: @card.customer_id, #顧客ID
    currency: 'jpy', #日本円
    )
    redirect_to done_item_path #完了画面に移動
  end

  def done
    @item = Item.find(params[:id])
    @item.update( purchaser_id: current_user.id)
    redirect_to root_path
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def set_item_image
    @item_images = ItemImage.includes(:item)
  end

  def item_params
    params.require(:item).permit(
      :name,
      :description,
      :category_id,
      :size_id,
      :state_id,
      :postage_side_id,
      :send_method_id,
      :prefecture_id,
      :send_date_id,
      :price,
      item_images_attributes: [:image],
      brand_attributes: [:id, :name],
      
    ).merge(user_id: current_user.id)
  end

  def set_all
    @size = Size.all
    @state = State.all
    @postage_side = PostageSide.all
    @send_method = SendMethod.all
    @prefecture = Prefecture.all
    @send_date = SendDate.all
  end
  def set_card
    @card = current_user.cards.first
  end
  def set_item_category
    #セレクトボックスの初期値設定
    @parents = ["---"]
    #データベースから、親カテゴリーのみ抽出し、配列化
    Category.where(ancestry: nil).each do |parent|
      @parents << parent.name
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper

  def converting_to_jpy(price)
    "¥#{price.to_s(:delimited, delimiter: ',')}"
  end

end

app/views/items/_footer.html.haml
%asid.advertisement
  .advertisement-image
    .contents
      .contents__detail
        .contents__detail__text-a
          スマホでかんたんフリマアプリ
        .contents__detail__text-b
          今すぐ無料ダウンロード!!
        .contents__detail__link
          =image_tag "logo_red.png",class:"log-red-only"
          =link_to "#",class:"apple" do
            =image_tag "image-apple.png",class:"apple"
          =link_to "#",class:"google" do
            =image_tag "en_badge_web_generic.png",class:"google"
.main-footer
  .main-footer__detail
    .main-footer__detail__fmarket
      =link_to "#",class:"main-footer__detail__fmarket__title" do
        Fmarketについて
      .main-footer__detail__fmarket__texts
        =link_to "#",class:"main-footer__detail__fmarket__texts__text" do
          会社概要(運営会社)
        =link_to "#",class:"main-footer__detail__fmarket__texts__text" do
          採用情報
        =link_to "#",class:"main-footer__detail__fmarket__texts__text" do
          プレスリリース
        =link_to "#",class:"main-footer__detail__fmarket__texts__text" do
          公式ブログ
        =link_to "#",class:"main-footer__detail__fmarket__texts__text" do
          Fmarketロゴ利用ガイドライン
      =link_to "#",class:"main-footer__detail__fmarket__icon" do
        %i.fa.fa-facebook.fa-3x
      =link_to "#",class:"main-footer__detail__fmarket__icon" do
        %i.fa.fa-twitter.fa-3x
    .main-footer__detail__help
      =link_to "#",class:"main-footer__detail__help__title" do
        ヘルプ＆ガイド
      .main-footer__detail__help__texts
        =link_to "#",class:"main-footer__detail__help__texts__text" do
          FMガイド
        =link_to "#",class:"main-footer__detail__help__texts__text" do
          楽々FM便
        =link_to "#",class:"main-footer__detail__help__texts__text" do
          ゆうゆうFM便
        =link_to "#",class:"main-footer__detail__help__texts__text" do
          大型FM便
        =link_to "#",class:"main-footer__detail__help__texts__text" do
          車体取引ガイド
        =link_to "#",class:"main-footer__detail__help__texts__text" do
          FMあんしん・あんぜん宣言！
        =link_to "#",class:"main-footer__detail__help__texts__text" do
          偽ブランド品撲滅への取り組み
        =link_to "#",class:"main-footer__detail__help__texts__text" do
          FMボックス
    .main-footer__detail__privacy-policy
      =link_to "#",class:"main-footer__detail__privacy-policy__title" do
        プライバシーと利用規約
      .main-footer__detail__privacy-policy__text
        .main-footer__detail__privacy-policy__text__privacies
          =link_to "#",class:"main-footer__detail__privacy-policy__text__privacies__privacy" do
            プライバシーポリシー
          =link_to "#",class:"main-footer__detail__privacy-policy__text__privacies__privacy" do
            FM利用規約
          =link_to "#",class:"main-footer__detail__privacy-policy__text__privacies__privacy" do
            あんしんスマホサポート制度に関する利用規約
          =link_to "#",class:"main-footer__detail__privacy-policy__text__privacies__privacy" do
            コンプライアンスポリシー
        .main-footer__detail__privacy-policy__texts__terms
          =link_to "#",class:"main-footer__detail__privacy-policy__text__terms__a" do
            個人データの安全管理に係る基本方針
          =link_to "#",class:"main-footer__detail__privacy-policy__text__terms__a" do
            特定商取引に関する表記
          =link_to "#",class:"main-footer__detail__privacy-policy__text__terms__a" do
            資金決済法に基づく表示
          =link_to "#",class:"main-footer__detail__privacy-policy__text__terms__a" do
            法令順守と犯罪抑止のため
    .main-footer__detail__country
      =link_to "#",class:"main-footer__detail__country__titile" do
        国
      .main-footer__detail__country__detail
        =link_to "#",class:"main-footer__detail__country__detail__name" do
          日本
        =link_to "#",class:"main-footer__detail__country__detail__name" do
          United States
  .main-footer__end
    =link_to root_path,class:"main-footer__end__log" do
      =image_tag "logo_white.png",class:"main-footer__end__log"
    .main-footer__end__copy
      ©️Fmerket

app/views/items/_header.html.haml
.main-header
  .main-header__center
    .main-header__center__title
      .main-header__center__title--logo
        =link_to root_path do
          =image_tag "fmarket_logo_red.png",class:"logo"
      %input{placeholder:"何かお探しですか？？",class:"main-header__center__title__search"}
      %i.fa.fa-search.fa-2x
    .main-header__center__contents
      .main-header__center__contents__types
        =link_to "#",class:"main-header__center__contents__types--category" do
          %i.fa.fa-list-alt
          カテゴリから探す
        =link_to "#",class:"main-header__center__contents__types--bland" do
          %i.fa.fa-ellipsis-v
          ブランドから探す
      - if user_signed_in?
        .main-header__center__contents__other
          =link_to "#",class:"main-header__center__contents__other__iine" do
            %i.fa.fa-heart
            いいね！一覧
          =link_to "#",class:"main-header__center__contents__other__news" do
            %i.fa.fa-bell
            お知らせ
          =link_to "#",class:"main-header__center__contents__other__do" do
            %i.fa.fa-check
            やることリスト
          =link_to user_path(current_user) ,class:"main-header__center__contents__other__mypage" do
            =image_tag "iconmonstr-user-5-240.png",class:"nill-image"
            %i.fa.fa-grin-squint
            マイページ
      - else
        .main-header__center__contents__new
          =link_to new_user_path,class:"main-header__center__contents__new__entry" do
            新規会員登録
          =link_to new_user_session_path,class:"main-header__center__contents__new__login" do
            ログイン

app/views/items/_index-bland.html.haml
- @items.each do |item|
  %li.main-detail__bland-item__list__contents__detail
    =link_to item_path(item.id),class:"main-detail__bland-item__list__contents__detail__content" do
      .main-detail__bland-item__list__contents__detail__content__aline
        .main-detail__category-item__list__contents__detail__content__aline__image
          = image_tag item.item_images.first.image.url.to_s,class:"image"
          .main-detail__bland-item__list__contents__detail__content__aline__image__fee
            = converting_to_jpy(item.price)
          -if item.purchaser_id.present?
            .main-detail__category-item__list__contents__detail__content__aline__sold
              .main-detail__category-item__list__contents__detail__content__aline__sold__inner
                SOLD
        .main-detail__bland-item__list__contents__detail__content__aline__text
          = item.name

app/views/items/_index-item.html.haml
- @items.each do |item|
  %li.main-detail__category-item__list__contents__detail
    =link_to item_path(item.id), class:"main-detail__category-item__list__contents__detail__content" do
      .main-detail__category-item__list__contents__detail__content__aline
        .main-detail__category-item__list__contents__detail__content__aline__image
          = image_tag item.item_images.first.image.url.to_s,class:"image"
          .main-detail__category-item__list__contents__detail__content__aline__image__fee
            = converting_to_jpy(item.price)
          -if item.purchaser_id.present?
            .main-detail__category-item__list__contents__detail__content__aline__sold
              .main-detail__category-item__list__contents__detail__content__aline__sold__inner
                SOLD
        .main-detail__category-item__list__contents__detail__content__aline__text
          = item.name

app/views/items/_show_item.html.haml
- @items.each do |item|
  %li.item__contents__content
    =link_to item_path(item.id) do
      .item__contents__content__image
        = image_tag item.item_images[0].image.url.to_s, class: "item__contents__content__image__photo"
      .item__contents__content__details
        .item__contents__content__details__name
          = item.name
      .item__contents__content__price
        = converting_to_jpy(item.price)
        = fa_icon "heart", class: "item__contents__content__price__good"

app/views/items/index.html.haml
-# トップページ
- if user_signed_in?
  =link_to new_item_path do
    .main-page__send-btn
      .main-page__send-btn__name
        出品
      .main-page__send-btn__detail
        %i.fa.fa-camera.fa
- else
  =link_to new_user_path do
    .main-page__send-btn
      .main-page__send-btn__name
        出品
      .main-page__send-btn__detail
        %i.fa.fa-camera.fa
=render partial: "items/header"
.swiper-containers
  = image_tag "grand-canyon-1839279_1920.jpg",class:"swiper-containers__image"
.main-detail
  .main-detail__category
    .main-detail__category__title
      .main-detail__category__title__theme
        人気のカテゴリー
      .main-detail__category__title__method
        =link_to "#",class:"main-detail__category__title__method__name" do
          メンズ
        =link_to "#",class:"main-detail__category__title__method__name" do
          レディース
        =link_to "#",class:"main-detail__category__title__method__name" do
          家電・スマホ・カメラ
        =link_to "#",class:"main-detail__category__title__method__name" do
          おもちゃ・ホビー・グッズ
  .main-detail__category-item
    .main-detail__category-item__title
      .main-detail__category-item__title__name
        新着アイテム
      =link_to "#",class:"main-detail__category-item__title__see-more" do
        もっと見る
    .main-detail__category-item__list
      %ul.main-detail__category-item__list__contents
        =render partial: "items/index-item"
  .main-detail__bland
    .main-detail__bland__title
      .main-detail__bland__title__theme
        人気のブランド
      .main-detail__bland__title__method
        =link_to "#",class:"main-detail__bland__title__method__name" do
          シャレル
        =link_to "#",class:"main-detail__bland__title__method__name" do
          レイヴィトン
        =link_to "#",class:"main-detail__bland__title__method__name" do
          シュリーム
        =link_to "#",class:"main-detail__bland__title__method__name" do
          ネイキ
  .main-detail__bland-item
    .main-detail__bland-item__title
      .main-detail__bland-item__title__name
        新着アイテム
      =link_to "#",class:"main-detail__bland-item__title__see-more" do
        もっと見る
    .main-detail__bland-item__list
      %ul.main-detail__bland-item__list__contents
        =render partial: "items/index-bland"
=render partial: "items/footer"

app/views/items/new.html.haml
-# 商品の出品画面
.item_new_container
  
  .header
    = link_to root_path do
      = image_tag 'fmarket_logo_red.png', class: 'header__logo'

  .sell-main
    %h2.sell-main__header
      商品の情報を入力
    
    = form_for @item, url: items_path, method: :post do |f|
      /画像
      .sell-main__form__container
        %h3.sell-form__upload__title
          出品画像
          %span.form-require
            必須
        %p.sell-form__upload__text
          最大10枚までアップロードできます
        = f.fields_for :item_images do |i|
          .upload_box
            = i.label :image, class: 'sell-form__upload__box' do
              %p.sell-form__upload__box__text
                ドラッグアンドドロップ
                %br
                  またはクリックしてファイルをダウンロード
              = i.file_field :image, multiple: true, type: 'file', name: "item_images[image][]", class: 'sell-form__upload__box__file'
              = i.file_field :image, multiple: true, type: 'file', name: "item_images[image][]", class: 'sell-form__upload__box__file'
              = i.file_field :image, multiple: true, type: 'file', name: "item_images[image][]", class: 'sell-form__upload__box__file'
              = i.file_field :image, multiple: true, type: 'file', name: "item_images[image][]", class: 'sell-form__upload__box__file'
              = i.file_field :image, multiple: true, type: 'file', name: "item_images[image][]", class: 'sell-form__upload__box__file'
              = i.file_field :image, multiple: true, type: 'file', name: "item_images[image][]", class: 'sell-form__upload__box__file'
              = i.file_field :image, multiple: true, type: 'file', name: "item_images[image][]", class: 'sell-form__upload__box__file'
              = i.file_field :image, multiple: true, type: 'file', name: "item_images[image][]", class: 'sell-form__upload__box__file'
              = i.file_field :image, multiple: true, type: 'file', name: "item_images[image][]", class: 'sell-form__upload__box__file'
              = i.file_field :image, multiple: true, type: 'file', name: "item_images[image][]", class: 'sell-form__upload__box__file'
      /商品
      .sell-main__form__container
        .sell-form__item__name
          %h4.form-title
            商品名
            %span.form-require
              必須
          = f.text_field :name, placeholder: "商品名（必須40文字まで）", class: 'sell-form__item__name__input form-style'
        .sell-form__item__description
          %h4.form-title
            商品の説明
            %span.form-require
              必須
          = f.text_area :description, placeholder: "商品の説明（必須1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。合わせやすいのでおすすめです。", class: 'sell-form__item__description__input'

      /詳細
      .sell-main__form__container
        .sell-form__item__detail
          %h4.sell-form__item__detail__title
            商品の詳細
          .sell-form__item__detail__content
            .sell-form__item__detail__content__category
              %h4.form-title
                カテゴリー
                %span.form-require
                  必須
              = f.select :category_id, @parents, {}, {class: 'form-select-2 form-style-new select-form', id: 'parent_category'}
            .sell-form__item__detail__content__size
              %h4.form-title
                サイズ
                %span.form-require
                  必須
              = f.collection_select :size_id, @size, :id, :text, {prompt: '---'}, {class: 'form-select form-style'}
            = f.fields_for :brand do |b|
              .sell-form__item__detail__content__brand
                %h4.form-title
                  ブランド
                  %span.form-arbitrary
                    任意
                = b.text_field :name, placeholder: "例）シャネル", class: 'sell-form__item__detail__content__brand__input form-style'
            .sell-form__item__detail__content__states
              %h4.form-title
                商品の状態
                %span.form-require
                  必須
              = f.collection_select :state_id, @state, :id, :text, {prompt: '---'}, {class: 'form-select form-style'}

      /配送
      .sell-main__form__container
        .sell-form__delivery
          .sell-form__delivery--left
            %h4.sell-form__delivery--left__title
              配送について
            = link_to '#', class: 'content-question' do
              ?
          .sell-form__delivery--right
            .sell-form__delivery--right__fee
              %h4.form-title
                配送料の負担
                %span.form-require
                  必須
              = f.collection_select :postage_side_id, @postage_side, :id, :text, {prompt: '---'}, {class: 'form-select form-style'}
            .sell-form__delivery--right__method
              %h4.form-title
                配送の方法
                %span.form-require
                  必須
              = f.collection_select :send_method_id, @send_method, :id, :text, {prompt: '---'}, {class: 'form-select form-style'}
            .sell-form__delivery--right__prefecture
              %h4.form-title
                発送元の地域
                %span.form-require
                  必須
              = f.collection_select :prefecture_id, @prefecture, :id, :name, {prompt: '---'}, {class: 'form-select form-style'}
            .sell-form__delivery--right__days
              %h4.form-title
                発送までの日数
                %span.form-require
                  必須
              = f.collection_select :send_date_id, @send_date, :id, :text, {prompt: '---'}, {class: 'form-select form-style'}

      /価格
      .sell-main__form__container
        .sell-form__price
          .sell-form__price--left
            %h4.sell-form__price--left__title
              販売価格(300~9,999,999)
            = link_to '#', class: 'content-question' do
              ?
          .sell-form__price--right
            .sell-form__price--right__price
              %h4.form-title
                価格
                %span.form-require
                  必須
                %span.yen-mark
                  ¥
                %span
                  = f.text_field :price, placeholder: "例）300", class: 'sell-form__price--right__price__input form-style', id: "price"
            .sell-form__price--right__fee
              %p.sell-form__price--right__fee--left
                販売手数料(10%)
              %p.sell-form__price--right__fee--right
                ー
            .sell-form__price--right__profit
              %p.sell-form__price--right__profit--left
                販売利益
              %p.sell-form__price--right__profit--right
                ー

      /注意書き
      .sell-main__form__container
        %p.sell-form__text
          = link_to '#', class: 'sell-form__text__link' do
            禁止されている出品
          、
          = link_to '#', class: 'sell-form__text__link' do
            行為
          を必ずご確認ください。
          %br
          またブランド品でシリアルナンバー等がある場合はご記載ください。
          = link_to '#', class: 'sell-form__text__link' do
            偽ブランドの販売
          は犯罪であり処罰される可能性があります。
          %br
          また、出品をもちまして
          = link_to '#', class: 'sell-form__text__link' do
            加盟店規約
          に同意したことになります。

        /出品
        = f.submit "出品する", class: 'red-btn'

        = link_to root_path, class: 'sell-return-btn' do
          もどる

  .footer
    .footer__contents
      = link_to '#', class: 'footer__contents__content' do
        プライバシーポリシー
      = link_to '#', class: 'footer__contents__content' do
        メルカリ利用規約
      = link_to '#', class: 'footer__contents__content' do
        特定商取引に関する表記
    = link_to '#' do
      = image_tag 'logo_gray.png', class: 'footer__logo'
    .footer__c
      ©︎ 2019 Fmarket

app/views/items/show.html.haml
-# ヘッダー
= render "items/header"
-# 商品詳細画面
.item
  .item__page  
    .item__page__title
      .item__page__title__name
        = @item.name
    .item__page__data
      .item__page__data__photo-box
        .item__page__data__photo-box__photo
          = image_tag @images[0].image.to_s, class: "item__page__data__photo-box__photo__image"
          - if @item.purchaser_id.present?
            .item__page__data__photo-box__photo__image__sold
              .item__page__data__photo-box__photo__image__sold__inner
                SOLD
            .item__page__data__photo-box__photos
              - @images.each do |image|
                = image_tag image.image.to_s, class: "item__page__data__photo-box__photos__main"
          - else
            - @images.each do |image|
              = image_tag image.image.to_s, class: "item__page__data__photo-box__photos__main"
      %table.item__page__data__list
        %tr
          %th 出品者
          %td
            = link_to "#{@item.user.nickname}"
            .item__page__data__list__box
              .item__page__data__list__box__good
                = fa_icon "thumbs-up"
                29
              .item__page__data__list__box__normal
                = fa_icon "thumbs-up"
                29
              .item__page__data__list__box__bad
                = fa_icon "thumbs-up"
                29
        %tr
          %th カテゴリー
          %td
            - if @item.category.nil?
            - else
              = @item.category.name
        %tr
          %th ブランド
          %td
            - if @item.brand.nil?
            - else
              = @item.brand.name
        %tr
          %th 商品の状態
          %td
            = @item.state.text
        %tr
          %th 配送料の負担
          %td 
            = @item.postage_side.text
        %tr
          %th 配送の方法
          %td 
            = @item.send_method.text
        %tr
          %th 配送元地域
          %td
            = @item.prefecture.name
        %tr
          %th 発送日の目安
          %td 
            = @item.send_date.text

    .item__page__price
      .item__page__price__number
        = converting_to_jpy(@item.price)
      .item__page__price__tax
        (税込)
      .item__page__price__postage
        送料込み
    - if user_signed_in? && current_user.id == @item.user_id && @item.purchaser_id.present?
      = link_to "この商品は売り切れました", root_path, class: "item__page__delete"
      = link_to "商品の削除", item_path(@item.id), method: :delete, class: "item__page__delete"
    - elsif user_signed_in? && current_user.id == @item.user_id
      = link_to "商品の編集", edit_item_path, class: "item__page__buy"
      = link_to "商品の削除", item_path(@item.id), method: :delete, class: "item__page__delete"
    - elsif user_signed_in? && @item.purchaser_id.present?
      = link_to "この商品は売り切れました", root_path, class: "item__page__delete"
    - elsif user_signed_in?
      = link_to "購入画面に進む", buy_item_path(@item.id), class: "item__page__buy"
    - else
      = link_to "購入にはログインが必要です", new_user_session_path, class: "item__page__delete"
    .item__page__text
      = @item.description
    .item__page__button
      .item__page__button__left
        %button.item__page__button__left__like{type: "button"}
          .item__page__button__left__like__heart
            = fa_icon "heart" 
            .item__page__button__left__like__good
              いいね! 29
        %button.item__page__button__left__report{type: "button"}
          .item__page__button__left__report__flag
            = fa_icon "flag"
            不適切な商品の報告
        = link_to "#", class: "item__page__button__right" do
          = fa_icon "lock"
          あんしん・あんぜんへの取り組み
      
  %form.item__comment 
    .item__comment__attention
      相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
    %textarea{type: "text",class: "item__comment__textarea"}
    %button{type: "submit" , class: "item__comment__button"}
      コメントする
  .item__media
    = link_to "https://www.facebook.com/", class: "item__media__facebook" do
      = fa_icon "facebook-square"
    = link_to "https://twitter.com/", class: "item__media__twitter" do
      = fa_icon "twitter-square"
    = link_to "https://www.pinterest.jp/", class: "item__media__pinterest" do
      = fa_icon "pinterest-square"
  .item__user
    = link_to "#{@item.user.nickname}さんのその他の商品", "#", style: "font-size:15pt;font-weight:bold;", class: "item__user__items"
  %ul.item__contents
    = render partial: "items/show_item"
  .item__bottom
    .item__bottom__item
      =render 'shared/breadcrumbs'

-# フッター
= render "items/footer"